#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PAYUUPIBOLTBASEKIT_SWIFT_H
#define PAYUUPIBOLTBASEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayUUPIBoltBaseKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltAccountDetail")
@interface PayUUPIBoltAccountDetail : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nullable accountId;
@property (nonatomic, copy) NSString * _Nullable accountNo;
@property (nonatomic, copy) NSString * _Nullable accountName;
@property (nonatomic, copy) NSString * _Nullable accountType;
@property (nonatomic, copy) NSString * _Nullable bankId;
@property (nonatomic, copy) NSString * _Nullable bankName;
@property (nonatomic, copy) NSString * _Nullable bankCode;
@property (nonatomic, copy) NSString * _Nullable credentialType;
@property (nonatomic, copy) NSString * _Nullable credentialLength;
@property (nonatomic, copy) NSString * _Nullable aeba;
@property (nonatomic, copy) NSString * _Nullable mmid;
@property (nonatomic, copy) NSString * _Nullable mbeba;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable ifsc;
@property (nonatomic, copy) NSString * _Nullable iin;
@property (nonatomic, copy) NSString * _Nullable formatType;
@property (nonatomic, copy) NSString * _Nullable atmdLength;
@property (nonatomic, copy) NSString * _Nullable otpdLength;
@property (nonatomic, copy) NSString * _Nullable dLength;
@property (nonatomic, copy) NSString * _Nullable atmdType;
@property (nonatomic, copy) NSString * _Nullable otpdType;
@property (nonatomic, copy) NSString * _Nullable dType;
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable defVPAStatus;
@property (nonatomic, copy) NSString * _Nullable defaultFlag;
@property (nonatomic, copy) NSString * _Nullable customerName;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable refUrl;
@property (nonatomic, copy) NSString * _Nullable refId;
@property (nonatomic, copy) NSString * _Nullable cardType;
@property (nonatomic, copy) NSString * _Nullable cardNo;
@property (nonatomic, copy) NSString * _Nullable expiry;
@property (nonatomic, copy) NSString * _Nullable balance;
@property (nonatomic, copy) NSString * _Nullable baltime;
@property (nonatomic, copy) NSString * _Nullable intlAccFlag;
@property (nonatomic, copy) NSString * _Nullable preferredFlag;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit22PayUUPIBoltAccountInfo")
@interface PayUUPIBoltAccountInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable pspRespRefNo;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable vpaSuggestionList;
@property (nonatomic, copy) NSArray<PayUUPIBoltAccountDetail *> * _Nullable accountList;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit21PayUUPIBoltAddAccount")
@interface PayUUPIBoltAddAccount : NSObject
@property (nonatomic, copy) NSString * _Nullable response;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltBalanceDetail")
@interface PayUUPIBoltBalanceDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable accBalance;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltBalanceEnquiryDetail;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit25PayUUPIBoltBalanceEnquiry")
@interface PayUUPIBoltBalanceEnquiry : NSObject
@property (nonatomic, copy) NSString * _Nullable statusDescription;
@property (nonatomic, copy) NSString * _Nullable npciTranId;
@property (nonatomic, strong) PayUUPIBoltBalanceEnquiryDetail * _Nullable accountInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit31PayUUPIBoltBalanceEnquiryDetail")
@interface PayUUPIBoltBalanceEnquiryDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable accId;
@property (nonatomic, copy) NSString * _Nullable ifscCode;
@property (nonatomic, copy) NSString * _Nullable uPinLength;
@property (nonatomic, copy) NSString * _Nullable bankId;
@property (nonatomic, copy) NSString * _Nullable accountBalance;
@property (nonatomic, copy) NSString * _Nullable accountName;
@property (nonatomic, copy) NSString * _Nullable optdLength;
@property (nonatomic, copy) NSString * _Nullable atmLength;
@property (nonatomic, copy) NSString * _Nullable accountNo;
@property (nonatomic, copy) NSString * _Nullable atmdLength;
@property (nonatomic, copy) NSString * _Nullable otpdLength;
@property (nonatomic, copy) NSString * _Nullable availableBal;
@property (nonatomic, copy) NSString * _Nullable otpCardLength;
@property (nonatomic, copy) NSString * _Nullable accountType;
@property (nonatomic, copy) NSString * _Nullable bankName;
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable otpCrdLength;
@property (nonatomic, copy) NSString * _Nullable otpLength;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltBankVersionDetail;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit21PayUUPIBoltBankDetail")
@interface PayUUPIBoltBankDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable bankId;
@property (nonatomic, copy) NSString * _Nullable bankName;
@property (nonatomic, copy) NSString * _Nullable ifsc;
@property (nonatomic, copy) NSString * _Nullable bankCode;
@property (nonatomic, copy) NSString * _Nullable statusCode;
@property (nonatomic, copy) NSString * _Nullable iin;
@property (nonatomic, copy) NSString * _Nullable formatType;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSArray<PayUUPIBoltBankVersionDetail *> * _Nullable versionList;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltRequestInfo;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit19PayUUPIBoltBankInfo")
@interface PayUUPIBoltBankInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, strong) PayUUPIBoltRequestInfo * _Nullable requestInfo;
@property (nonatomic, copy) NSArray<PayUUPIBoltBankDetail *> * _Nullable bankList;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit28PayUUPIBoltBankVersionDetail")
@interface PayUUPIBoltBankVersionDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable no;
@property (nonatomic, copy) NSString * _Nullable desc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit21PayUUPIBoltBaseConfig")
@interface PayUUPIBoltBaseConfig : NSObject
@property (nonatomic, copy) NSString * _Nonnull merchantKey;
@property (nonatomic, copy) NSString * _Nonnull merchantName;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull refId;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull pluginTypes;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull excludedBanksIINs;
@property (nonatomic, copy) NSString * _Nonnull clientId;
@property (nonatomic) BOOL isProduction;
@property (nonatomic) BOOL isProtectedScreen;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithMerchantName:(NSString * _Nonnull)merchantName merchantKey:(NSString * _Nonnull)merchantKey phone:(NSString * _Nonnull)phone email:(NSString * _Nonnull)email refId:(NSString * _Nonnull)refId pluginTypes:(NSArray<NSString *> * _Nonnull)pluginTypes excludedBanksIINs:(NSArray<NSString *> * _Nonnull)excludedBanksIINs clientId:(NSString * _Nonnull)clientId isProduction:(BOOL)isProduction OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit21PayUUPIBoltChangeMPIN")
@interface PayUUPIBoltChangeMPIN : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable npciTransId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltVpaPayeeList;
@class PayUUPIBoltVpaMerchantDetail;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit25PayUUPIBoltCheckVpaDetail")
@interface PayUUPIBoltCheckVpaDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSArray<PayUUPIBoltVpaPayeeList *> * _Nullable payeeList;
@property (nonatomic, copy) NSString * _Nullable paymentType;
@property (nonatomic) BOOL verificationFlag;
@property (nonatomic, strong) PayUUPIBoltVpaMerchantDetail * _Nullable merchantDetails;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit26PayUUPIBoltCustomerDispute")
@interface PayUUPIBoltCustomerDispute : NSObject
@property (nonatomic, copy) NSString * _Nullable ticketNo;
@property (nonatomic, copy) NSString * _Nullable pgMeTrnRefNo;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable storeId;
@property (nonatomic, copy) NSString * _Nullable crtDate;
@property (nonatomic, copy) NSString * _Nullable fvaddr;
@property (nonatomic, copy) NSString * _Nullable custid;
@property (nonatomic, copy) NSString * _Nullable targetDate;
@property (nonatomic, copy) NSString * _Nullable custRefNo;
@property (nonatomic, copy) NSString * _Nullable reqReasnDesc;
@property (nonatomic, copy) NSString * _Nullable txnid;
@property (nonatomic, copy) NSString * _Nullable txnRemark;
@property (nonatomic, copy) NSString * _Nullable amount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltUserInfo;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltDeregisterVPA")
@interface PayUUPIBoltDeregisterVPA : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, strong) PayUUPIBoltRequestInfo * _Nullable requestInfo;
@property (nonatomic, copy) NSString * _Nullable regRefId;
@property (nonatomic, strong) PayUUPIBoltUserInfo * _Nullable userInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit21PayUUPIBoltDeviceInfo")
@interface PayUUPIBoltDeviceInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable simSerialNo;
@property (nonatomic, copy) NSString * _Nullable androidId;
@property (nonatomic, copy) NSString * _Nullable appName;
@property (nonatomic, copy) NSString * _Nullable appGenId;
@property (nonatomic, copy) NSString * _Nullable appVersionCode;
@property (nonatomic, copy) NSString * _Nullable capability;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable deviceType;
@property (nonatomic, copy) NSString * _Nullable geoCode;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable mobileNo;
@property (nonatomic, copy) NSString * _Nullable os;
@property (nonatomic, copy) NSString * _Nullable relayButton;
@property (nonatomic, copy) NSString * _Nullable simId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit23PayUUPIBoltDeviceStatus")
@interface PayUUPIBoltDeviceStatus : NSObject
@property (nonatomic, strong) PayUUPIBoltDeviceInfo * _Nullable deviceInfo;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable errorCode;
@property (nonatomic, copy) NSString * _Nullable deviceStatus;
@property (nonatomic, copy) NSString * _Nullable simStatus;
@property (nonatomic, strong) PayUUPIBoltUserInfo * _Nullable userInfo;
@property (nonatomic, copy) NSString * _Nullable flowSimId;
@property (nonatomic, copy) NSString * _Nullable smsGateWayContent;
@property (nonatomic, copy) NSString * _Nullable smsGateWayKey;
@property (nonatomic, copy) NSString * _Nullable smsGateWayNo;
@property (nonatomic, copy) NSString * _Nullable smsStatus;
@property (nonatomic, copy) NSString * _Nullable npciTokenRefreshFlag;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit22PayUUPIBoltDisputeType")
@interface PayUUPIBoltDisputeType : NSObject
@property (nonatomic, copy) NSString * _Nullable reasonCode;
@property (nonatomic, copy) NSString * _Nullable reasonDesc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit16PayUUPIBoltError")
@interface PayUUPIBoltError : NSObject
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic) NSInteger errorCode;
- (nonnull instancetype)initWithMessage:(NSString * _Nullable)message code:(NSInteger)code OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nullable errorDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit25PayUUPIBoltGetDisputeList")
@interface PayUUPIBoltGetDisputeList : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable ticketNo;
@property (nonatomic, copy) NSString * _Nullable upiTranRefNo;
@property (nonatomic, copy) NSArray<PayUUPIBoltCustomerDispute *> * _Nullable listofCustDispute;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIUserProfileAccountDetail;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit21PayUUPIBoltGetProfile")
@interface PayUUPIBoltGetProfile : NSObject
@property (nonatomic, copy) NSString * _Nullable notificationCount;
@property (nonatomic, copy) NSString * _Nullable defaultVPAStatus;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, strong) PayUUPIBoltUserInfo * _Nullable userInfo;
@property (nonatomic, copy) NSArray<PayUUPIUserProfileAccountDetail *> * _Nullable vpaAccountDetails;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltHashConstants")
@interface PayUUPIBoltHashConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull hashString;)
+ (NSString * _Nonnull)hashString SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull hashType;)
+ (NSString * _Nonnull)hashType SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull hashName;)
+ (NSString * _Nonnull)hashName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull postSalt;)
+ (NSString * _Nonnull)postSalt SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltInitiateMPINPayerType;
@class PayUUPIBoltInitiateMPINCredential;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit23PayUUPIBoltInitiateMPIN")
@interface PayUUPIBoltInitiateMPIN : NSObject
@property (nonatomic, copy) NSString * _Nullable upiTransactionRefNo;
@property (nonatomic, copy) NSString * _Nullable npciTransactionId;
@property (nonatomic, copy) NSString * _Nullable otpNpciTransactionId;
@property (nonatomic, strong) PayUUPIBoltInitiateMPINPayerType * _Nullable payerType;
@property (nonatomic, copy) NSString * _Nullable transactionNote;
@property (nonatomic, copy) NSString * _Nullable refUrl;
@property (nonatomic, strong) PayUUPIBoltInitiateMPINCredential * _Nullable credential;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit33PayUUPIBoltInitiateMPINCredential")
@interface PayUUPIBoltInitiateMPINCredential : NSObject
@property (nonatomic, copy) NSString * _Nullable credentialDataType;
@property (nonatomic, copy) NSString * _Nullable credentialDataLength;
@property (nonatomic, copy) NSString * _Nullable atmCredentialLength;
@property (nonatomic, copy) NSString * _Nullable atmCredentialType;
@property (nonatomic, copy) NSString * _Nullable atmFormatType;
@property (nonatomic, copy) NSString * _Nullable otpCredentialLength;
@property (nonatomic, copy) NSString * _Nullable otpCredentialType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit32PayUUPIBoltInitiateMPINPayerType")
@interface PayUUPIBoltInitiateMPINPayerType : NSObject
@property (nonatomic, copy) NSString * _Nullable virtualAddress;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable payerBankName;
@property (nonatomic, copy) NSString * _Nullable accountNo;
@property (nonatomic, copy) NSString * _Nullable isMerchant;
@property (nonatomic) BOOL showMerchant;
@property (nonatomic) BOOL defaultVPAStatus;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit19PayUUPIBoltListKeys")
@interface PayUUPIBoltListKeys : NSObject
@property (nonatomic, copy) NSString * _Nullable txnId;
@property (nonatomic, copy) NSString * _Nullable refId;
@property (nonatomic, copy) NSString * _Nullable refUrl;
@property (nonatomic, copy) NSString * _Nullable xmlResp;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit22PayUUPIBoltMakePayment")
@interface PayUUPIBoltMakePayment : NSObject
@property (nonatomic, copy) NSString * _Nullable custRefNo;
@property (nonatomic) NSInteger upiTransRefNo;
@property (nonatomic, copy) NSString * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable txnAuthDate;
@property (nonatomic, copy) NSString * _Nullable responseCode;
@property (nonatomic, copy) NSString * _Nullable approvalNumber;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable accountId;
@property (nonatomic, copy) NSString * _Nullable payerVPA;
@property (nonatomic, copy) NSString * _Nullable payeeVPA;
@property (nonatomic, copy) NSString * _Nullable npciTransId;
@property (nonatomic, copy) NSString * _Nullable errorCode;
@property (nonatomic, copy) NSString * _Nullable payType;
@property (nonatomic, copy) NSString * _Nullable refId;
@property (nonatomic, copy) NSString * _Nullable prRespCode;
@property (nonatomic, strong) PayUUPIBoltRequestInfo * _Nullable requestInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit19PayUUPIBoltPGDetail")
@interface PayUUPIBoltPGDetail : NSObject
@property (nonatomic, copy) NSString * _Nonnull pg;
@property (nonatomic, copy) NSString * _Nonnull pgId;
@property (nonatomic, copy) NSString * _Nonnull merchChanId;
@property (nonatomic, copy) NSString * _Nonnull mcc;
@property (nonatomic, copy) NSString * _Nonnull merchId;
@property (nonatomic, copy) NSString * _Nonnull pluginKey;
- (nonnull instancetype)initWithPg:(NSString * _Nonnull)pg pgId:(NSString * _Nonnull)pgId merchChanId:(NSString * _Nonnull)merchChanId mcc:(NSString * _Nonnull)mcc merchId:(NSString * _Nonnull)merchId pluginKey:(NSString * _Nonnull)pluginKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit29PayUUPIBoltPayeeAccountDetail")
@interface PayUUPIBoltPayeeAccountDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable ifsc;
@property (nonatomic, copy) NSString * _Nullable mobile;
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable vpaType;
@property (nonatomic, copy) NSString * _Nullable mode;
@property (nonatomic, copy) NSString * _Nullable merchantId;
@property (nonatomic, copy) NSString * _Nullable mcc;
@property (nonatomic, copy) NSString * _Nullable purpose;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable nickName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUUPIBoltUserDefines;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltPaymentParams")
@interface PayUUPIBoltPaymentParams : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nonnull txnId;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull productInfo;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull surl;
@property (nonatomic, copy) NSString * _Nonnull furl;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalParam;
@property (nonatomic, strong) PayUUPIBoltUserDefines * _Nullable udfs;
@property (nonatomic, strong) PayUUPIBoltAccountDetail * _Nullable payerAccountDetail;
@property (nonatomic, strong) PayUUPIBoltPayeeAccountDetail * _Nullable payeeAccountDetail;
- (nonnull instancetype)initWithTxnId:(NSString * _Nonnull)txnId amount:(NSString * _Nonnull)amount productInfo:(NSString * _Nonnull)productInfo firstName:(NSString * _Nonnull)firstName surl:(NSString * _Nonnull)surl furl:(NSString * _Nonnull)furl OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PayUUPIDisputeComplaintInfo;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit23PayUUPIBoltRaiseDispute")
@interface PayUUPIBoltRaiseDispute : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable errCode;
@property (nonatomic, strong) PayUUPIDisputeComplaintInfo * _Nullable complaintInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit28PayUUPIBoltRegisterVpaDetail")
@interface PayUUPIBoltRegisterVpaDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, strong) PayUUPIBoltRequestInfo * _Nullable requestInfo;
@property (nonatomic, copy) NSString * _Nullable registrationDate;
@property (nonatomic, strong) PayUUPIBoltUserInfo * _Nullable userInfo;
@property (nonatomic, copy) NSString * _Nullable servGenId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltRemoveAccount")
@interface PayUUPIBoltRemoveAccount : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable errCode;
@property (nonatomic, strong) PayUUPIBoltRequestInfo * _Nullable requestInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit22PayUUPIBoltRequestInfo")
@interface PayUUPIBoltRequestInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable pspId;
@property (nonatomic, copy) NSString * _Nullable pspRefNo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit19PayUUPIBoltResponse")
@interface PayUUPIBoltResponse : NSObject
@property (nonatomic) NSInteger code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable referenceId;
@property (nonatomic) id _Nullable result;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit24PayUUPIBoltSecretDetails")
@interface PayUUPIBoltSecretDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable quesId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit33PayUUPIBoltServerGenIdRequestInfo")
@interface PayUUPIBoltServerGenIdRequestInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable pspId;
@property (nonatomic, copy) NSString * _Nullable pspRefNo;
@property (nonatomic, copy) NSString * _Nullable checksumFlag;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit18PayUUPIBoltSetMPIN")
@interface PayUUPIBoltSetMPIN : NSObject
@property (nonatomic, copy) NSString * _Nullable pspRefNo;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable npciTransId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit28PayUUPIBoltTransactionDetail")
@interface PayUUPIBoltTransactionDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable result;
@property (nonatomic, copy) NSString * _Nullable txnId;
@property (nonatomic, copy) NSString * _Nullable respCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;

SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit29PayUUPIBoltTransactionHistory")
@interface PayUUPIBoltTransactionHistory : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable txnId;
@property (nonatomic, copy) NSString * _Nullable refId;
@property (nonatomic, copy) NSDate * _Nullable dateTime;
@property (nonatomic, copy) NSString * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable debitAccount;
@property (nonatomic, copy) NSString * _Nullable debitVPA;
@property (nonatomic, copy) NSString * _Nullable debitBankName;
@property (nonatomic, copy) NSString * _Nullable creditAccount;
@property (nonatomic, copy) NSString * _Nullable creditVPA;
@property (nonatomic, copy) NSString * _Nullable creditBankName;
@property (nonatomic, copy) NSString * _Nullable query;
@property (nonatomic, copy) NSString * _Nullable queryStatus;
@property (nonatomic, copy) NSDate * _Nullable queryDate;
@property (nonatomic, copy) NSString * _Nullable queryId;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable beneficiaryName;
@property (nonatomic, copy) NSString * _Nullable mobileNumber;
@property (nonatomic, copy) NSString * _Nullable remarks;
@property (nonatomic, copy) NSString * _Nullable npciTxnId;
@property (nonatomic, copy) NSString * _Nullable payerVpa;
@property (nonatomic, copy) NSString * _Nullable payerAccountNumber;
@property (nonatomic, copy) NSString * _Nullable payerAccountType;
@property (nonatomic, copy) NSString * _Nullable payeeVpa;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable upiTransRefNo;
@property (nonatomic, copy) NSString * _Nullable updatedOn;
@property (nonatomic, copy) NSString * _Nullable txnStatus;
@property (nonatomic, copy) NSString * _Nullable payerBankName;
@property (nonatomic, copy) NSString * _Nullable payeeName;
@property (nonatomic) BOOL isRefreshing;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit28PayUUPIBoltTransactionStatus")
@interface PayUUPIBoltTransactionStatus : NSObject
@property (nonatomic) NSInteger upiTxnRefNo;
@property (nonatomic, copy) NSString * _Nullable npciTxnId;
@property (nonatomic, copy) NSString * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic) NSInteger txnRefNo;
@property (nonatomic, strong) PayUUPIBoltTransactionDetail * _Nullable txnStatusDetails;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit22PayUUPIBoltUserDefines")
@interface PayUUPIBoltUserDefines : NSObject
@property (nonatomic, copy) NSString * _Nullable udf1;
@property (nonatomic, copy) NSString * _Nullable udf2;
@property (nonatomic, copy) NSString * _Nullable udf3;
@property (nonatomic, copy) NSString * _Nullable udf4;
@property (nonatomic, copy) NSString * _Nullable udf5;
@property (nonatomic, copy) NSString * _Nullable udf6;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit19PayUUPIBoltUserInfo")
@interface PayUUPIBoltUserInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable virtualAddress;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable isMerchant;
@property (nonatomic, copy) NSString * _Nullable showMerchant;
@property (nonatomic) BOOL defVPAStatus;
@property (nonatomic, copy) NSString * _Nullable defaultFlag;
@property (nonatomic, copy) NSString * _Nullable custid;
@property (nonatomic, copy) NSString * _Nullable accId;
@property (nonatomic, strong) PayUUPIBoltSecretDetails * _Nullable secretDetails;
@property (nonatomic, copy) NSString * _Nullable mobileNo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit28PayUUPIBoltVerifyServerGenId")
@interface PayUUPIBoltVerifyServerGenId : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
@property (nonatomic, copy) NSString * _Nullable errcode;
@property (nonatomic, copy) NSString * _Nullable servGenId;
@property (nonatomic, strong) PayUUPIBoltServerGenIdRequestInfo * _Nullable requestInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit28PayUUPIBoltVpaMerchantDetail")
@interface PayUUPIBoltVpaMerchantDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable ifsc;
@property (nonatomic, copy) NSString * _Nullable accType;
@property (nonatomic, copy) NSString * _Nullable sid;
@property (nonatomic, copy) NSString * _Nullable iin;
@property (nonatomic, copy) NSString * _Nullable isVerified;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit23PayUUPIBoltVpaPayeeList")
@interface PayUUPIBoltVpaPayeeList : NSObject
@property (nonatomic, copy) NSString * _Nullable virtualAddress;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusDesc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit27PayUUPIDisputeComplaintInfo")
@interface PayUUPIDisputeComplaintInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable actionType;
@property (nonatomic, copy) NSString * _Nullable crn;
@property (nonatomic, copy) NSString * _Nullable expectedResolDate;
@property (nonatomic, copy) NSString * _Nullable ticketNo;
@property (nonatomic, copy) NSString * _Nullable txnId;
@property (nonatomic, copy) NSString * _Nullable disputeType;
@property (nonatomic, copy) NSString * _Nullable onBehalfOf;
@property (nonatomic, copy) NSString * _Nullable orgRrn;
@property (nonatomic, copy) NSString * _Nullable orgTxnDate;
@property (nonatomic, copy) NSString * _Nullable orgTxnId;
@property (nonatomic, copy) NSString * _Nullable rrn;
@property (nonatomic, copy) NSString * _Nullable userMsg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18PayUUPIBoltBaseKit31PayUUPIUserProfileAccountDetail")
@interface PayUUPIUserProfileAccountDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable crdLength;
@property (nonatomic, copy) NSString * _Nullable accountType;
@property (nonatomic, copy) NSString * _Nullable atmdLength;
@property (nonatomic, copy) NSString * _Nullable accNo;
@property (nonatomic, copy) NSString * _Nullable preferredFlag;
@property (nonatomic, copy) NSString * _Nullable otpdLength;
@property (nonatomic, copy) NSString * _Nullable accName;
@property (nonatomic, copy) NSString * _Nullable bankName;
@property (nonatomic, copy) NSString * _Nullable mpinFlag;
@property (nonatomic, copy) NSString * _Nullable refUrl;
@property (nonatomic, copy) NSString * _Nullable bankCode;
@property (nonatomic, copy) NSString * _Nullable ifscCode;
@property (nonatomic, copy) NSString * _Nullable bankId;
@property (nonatomic, copy) NSString * _Nullable aepsFlag;
@property (nonatomic, copy) NSString * _Nullable accId;
@property (nonatomic, copy) NSString * _Nullable crdType;
@property (nonatomic, copy) NSString * _Nullable formatType;
@property (nonatomic, copy) NSString * _Nullable intlAccFlag;
@property (nonatomic, copy) NSString * _Nullable virtualAddress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
