# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PayUUPIBoltSwiftSampleApp' do
  use_frameworks!
  pod 'PayUIndia-UPIBoltUIKit'
  pod 'PayUIndia-UPIBoltCoreKit'
end
